### ISSUE TITLE
Uncatchable error thrown when request returns error

### ISSUE THREAD

**Issue by climbingshag** [meritt/node-tumblr#18]
I'm sorry, but the comments reference the .js lib files, not the source files.

When request call inside the req function in request.js returns an error (line 68 of request.js) , the request returns 
error = <error msg>
body = undefined
response = undefined

and the library throws an error when it hits line 74 and tries to reference body.response.

Here's my error code:
TypeError: Cannot read property 'response' of undefined
  at Request._callback (/Projects/human/node_modules/tumblr/lib/request.js:74:41)
  at self.callback (/Projects/human/node_modules/request/request.js:199:22)
  at Request.EventEmitter.emit (events.js:95:17)
  at ClientRequest.self.clientErrorHandler (/Projects/human/node_modules/request/request.js:343:10)
  at ClientRequest.EventEmitter.emit (events.js:95:17)
  at Socket.socketErrorListener (http.js:1547:9)
  at Socket.EventEmitter.emit (events.js:95:17)
  at net.js:833:16
  at process._tickCallback (node.js:419:13)

The error is kind of heinous, because it occurs in the callback chain, and can't be caught.

**Comment by meritt** [comment]
Fix in https://github.com/meritt/node-tumblr/pull/28
