### ISSUE TITLE
Very Strange. blog.avatar(512, function (error, response) { is throwing and error! not sure how to fix

### ISSUE THREAD

**Issue by alexrmacleod** [meritt/node-tumblr#23]
Code was working but blog.avatar call stopped working. 

`

```
        var createAccounts = function() {

                var blog = new tumblr.Blog(tumblrAccountArray[i], oauth);
                i++

                //username - profile picture - website for parse

                var tumblrAccount = {};

                blog.info(function (error, response) {

                    if (error) {
                        throw new Error(error);
                    }
                    // console.log(response.blog);

                    console.log('blog.INFO.RES ------------');
                    console.log('blog.title ------------');
                    console.log(response.blog.title);
                    tumblrAccount.title = response.blog.title;

                    console.log('blog.user_name ------------');
                    console.log(response.blog.name);
                    tumblrAccount.user_name = response.blog.name;

                    console.log('blog.url ------------');
                    console.log(response.blog.url);
                    tumblrAccount.url = response.blog.url;

                    console.log('tumblrAccount ------------');

                    blog.avatar(512, function (error, response) {
                        if (error) {
                            throw new Error(error);
                        }
                        console.log('blog.AVATAR.RES ------------');
                        console.log(response.avatar_url);
                        tumblrAccount.avatar_url = response.avatar_url;

                        console.log(tumblrAccount);

                        // use kaiseki
                        kaiseki.createObject(className, tumblrAccount, function (err, res, body, success) {
                            console.log('object created = ', body);
                            console.log('object id = ', body.objectId);
                        });
                    });
                });


                if (i === tumblrAccountArray.length) {
                    clearInterval(timer);
                }
            }
```

`

error response in terminal 

`

TypeError: Cannot read property 'avatar_url' of undefined
    at String.<anonymous> (/Users/alex/Dropbox/Tipped/tumblr-scraper/tumblr.js:375:33)
    at Request._callback (/Users/alex/Dropbox/Tipped/tumblr-scraper/node_modules/tumblr/lib/request.js:74:19)
    at Request.self.callback (/Users/alex/Dropbox/Tipped/tumblr-scraper/node_modules/tumblr/node_modules/request/request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/alex/Dropbox/Tipped/tumblr-scraper/node_modules/tumblr/node_modules/request/request.js:1044:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/Users/alex/Dropbox/Tipped/tumblr-scraper/node_modules/tumblr/node_modules/request/request.js:965:12)
    at emitNone (events.js:72:20)

`

**Comment by meritt** [comment]
Fix in https://github.com/meritt/node-tumblr/pull/28
