### ISSUE TITLE
User module Unit Test failed. 

### ISSUE THREAD

**Issue by gregwym** [meritt/node-tumblr#9]
Using `alias` to create methods causing `undefined` oauth information. 

I don't really know the reason, so I bring it up to you to see whether there is a solution. Or we should just give up the `alias` way of creating methods. 

Here is the Unit Test result. 

```
$ nodeunit test

blog
✔ testInfo
✔ testAvatar
✔ testAvatarSize
✔ testLikes
✔ testPosts

user
✔ testInfo
✖ testDashboard

undefined

AssertionError: true == 
    at Object.ok (/.../local/node/lib/node_modules/nodeunit/lib/types.js:83:39)
    at Object.<anonymous> (/.../.../node-tumblr/test/user.js:28:12)
    at Request._callback (/.../.../node-tumblr/lib/request.js:67:19)
    at Request.self.callback (/.../.../node-tumblr/node_modules/request/index.js:148:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/.../.../node-tumblr/node_modules/request/index.js:876:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/.../.../node-tumblr/node_modules/request/index.js:827:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:910:16
    at process._tickCallback (node.js:415:13)

✖ testLikes

undefined

AssertionError: true == 
    at Object.ok (/.../local/node/lib/node_modules/nodeunit/lib/types.js:83:39)
    at Object.<anonymous> (/.../.../node-tumblr/test/user.js:36:12)
    at Request._callback (/.../.../node-tumblr/lib/request.js:67:19)
    at Request.self.callback (/.../.../node-tumblr/node_modules/request/index.js:148:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/.../.../node-tumblr/node_modules/request/index.js:876:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/.../.../node-tumblr/node_modules/request/index.js:827:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:910:16
    at process._tickCallback (node.js:415:13)

✖ testFollowing

undefined

AssertionError: true == 
    at Object.ok (/.../local/node/lib/node_modules/nodeunit/lib/types.js:83:39)
    at Object.<anonymous> (/.../.../node-tumblr/test/user.js:44:12)
    at Request._callback (/.../.../node-tumblr/lib/request.js:67:19)
    at Request.self.callback (/.../.../node-tumblr/node_modules/request/index.js:148:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/.../.../node-tumblr/node_modules/request/index.js:876:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/.../.../node-tumblr/node_modules/request/index.js:827:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:910:16
    at process._tickCallback (node.js:415:13)


FAILURES: 6/29 assertions failed (2151ms)
```

**Comment by meritt** [comment]
It's my fault. Merged and published to npm.

**Comment by gregwym** [comment]
No worry, everything cool now. Thanks!
